# Generated by Django 5.2.8 on 2025-11-12 11:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Editora')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Empréstimo')),
                ('data_devolucao_prevista', models.DateField(verbose_name='Data de Devolução Prevista')),
                ('devolvido', models.BooleanField(default=False, verbose_name='Devolvido')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_exemplar', models.CharField(max_length=50, unique=True, verbose_name='Código do Exemplar')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Empréstimo')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('condicao', models.CharField(choices=[('EX', 'Excelente'), ('BO', 'Boa'), ('RE', 'Regular'), ('DE', 'Desgastada')], default='BO', max_length=2, verbose_name='Condição')),
            ],
            options={
                'verbose_name': 'Exemplar',
                'verbose_name_plural': 'Exemplares',
                'ordering': ['livro__titulo', 'codigo_exemplar'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Gênero')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('data_adesao', models.DateField(auto_now_add=True, verbose_name='Data de Adesão')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['sobrenome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['sobrenome', 'nome'],
                'unique_together': {('nome', 'sobrenome')},
            },
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao_real', models.DateTimeField(auto_now_add=True, verbose_name='Data da Devolução Real')),
                ('multa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor da Multa')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('emprestimo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.emprestimo', verbose_name='Empréstimo Referente')),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
                'ordering': ['-data_devolucao_real'],
            },
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='exemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.exemplar', verbose_name='Exemplar Emprestado'),
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('ano_publicacao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Ano de Publicação')),
                ('isbn', models.CharField(help_text='13 Caracteres ISBN', max_length=13, unique=True, verbose_name='ISBN')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('capa', models.FileField(blank=True, null=True, upload_to='capas/', verbose_name='Capa do Livro')),
                ('autores', models.ManyToManyField(to='biblioteca_app.autor', verbose_name='Autores')),
                ('editora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca_app.editora', verbose_name='Editora')),
                ('generos', models.ManyToManyField(to='biblioteca_app.genero', verbose_name='Gêneros')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='exemplar',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.livro', verbose_name='Livro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.membro', verbose_name='Membro'),
        ),
    ]
